### ISSUE TITLE
Simulation Object should throw exception if the input file fails to open

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/pyswmm#182]
Assuming pswmm v0.4.8. User did no confirm what version they were using. 

A pyswmm user tried opening the attached SWMM input file  and received the following exception:

```
code: 

from pyswmm import Simulation, Nodes
with Simulation('.\tutorial.inp') as sim:
...      node_object = Nodes(sim)
...      J1 = node_object["J1"]
...      print(J1.invert_elevation)
...      for step in sim:
...                  print(J1.total_inflow)
...      sim.report()
```
```
Traceback (most recent call last):

 File "<ipython-input-8-432624cfb1a1>", line 1, in <module>
   runfile('//eawag/userdata/dellicri/Desktop/SMWW/pyw_and_geo/file1.py', wdir='//eawag/userdata/dellicri/Desktop/SMWW/pyw_and_geo')

 File "C:\myPrograms\Anaconda3_32bit\envs\pys_and_geo\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 704, in runfile
   execfile(filename, namespace)

 File "C:\myPrograms\Anaconda3_32bit\envs\pys_and_geo\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
   exec(compile(f.read(), filename, 'exec'), namespace)

 File "//eawag/userdata/dellicri/Desktop/SMWW/pyw_and_geo/file1.py", line 19, in <module>
   J1 = node_object["J1"]

 File "C:\myPrograms\Anaconda3_32bit\envs\pys_and_geo\lib\site-packages\pyswmm\nodes.py", line 95, in __getitem__
   nd = Node(self._model, nodeid)

 File "C:\myPrograms\Anaconda3_32bit\envs\pys_and_geo\lib\site-packages\pyswmm\nodes.py", line 147, in __init__
   if nodeid not in model.getObjectIDList(ObjectType.NODE.value):

 File "C:\myPrograms\Anaconda3_32bit\envs\pys_and_geo\lib\site-packages\pyswmm\swmm5.py", line 660, in getObjectIDList
   IDS.append(self.getObjectId(objecttype, index))

 File "C:\myPrograms\Anaconda3_32bit\envs\pys_and_geo\lib\site-packages\pyswmm\swmm5.py", line 638, in getObjectId
   ctypes.byref(ID))

OSError: exception: access violation reading 0x00000000
```

It appears that the error occurs because their code attempted to query pyswmm for a node id when the input file failed to open. It would be more user friendly for the `Simulation` object to check and throw an exception when the input file fails to open rather than failing somewhere else for a seemingly unrelated reason. 

It is hypothesized that the input file requires SWMM v5.1.13 features but that pyswmm v0.4.8 supports SWMM v5.1.12. If this is indeed the case it would be helpful if users were warned of a SWMM version mismatch upon opening an input file. This could be accomplished by creating an entry in the input file that specifies the minimum version of SWMM sufficient to run the file and for the parser to issue an error if the version of SWMM currently being used does not satisfy the requirement. 

[example2.txt](https://github.com/OpenWaterAnalytics/pyswmm/files/2830030/example2.txt)

**Comment by sjhabedin** [comment]
I ma having the same issue. I am using SWMM 5.1.012. I don't know exactly where the problem lies. Any idea would be appreciated.
>>> with Simulation('C:\Research_SWMM\Wilket Creek.inp')as sim:
	node_object=Nodes(sim)
	J1=node_object["J1"]
	print(J1.invert_elevation)
	for step in sim:
		print(J1.total_inflow)
	sim.report()

Traceback (most recent call last):
  File "<pyshell#11>", line 3, in <module>
    J1=node_object["J1"]
  File "C:\Users\JOY\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyswmm\nodes.py", line 95, in __getitem__
    nd = Node(self._model, nodeid)
  File "C:\Users\JOY\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyswmm\nodes.py", line 147, in __init__
    if nodeid not in model.getObjectIDList(ObjectType.NODE.value):
  File "C:\Users\JOY\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyswmm\swmm5.py", line 660, in getObjectIDList
    IDS.append(self.getObjectId(objecttype, index))
  File "C:\Users\JOY\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyswmm\swmm5.py", line 638, in getObjectId
    ctypes.byref(ID))
OSError: exception: access violation reading 0x00000000

**Comment by arashtavakoli** [comment]
Has anyone found a solution for this? I am having the same problem

**Comment by bemcdonnell** [comment]
What does your RPT file say?

**Comment by arashtavakoli** [comment]
you mean the title of it? cause it does not even run. Also something funny, if I run the whole thing at once I get the error for the dll missing file too but if I run it in two separate section (before the while loop and after the while loop) then I get the access violation error

**Comment by arashtavakoli** [comment]
this is the error 

  File "<input>", line 13, in <module>
  File "C:\Users\Arsalan\Anaconda3\envs\RL_Project_S19\lib\site-packages\pyswmm\nodes.py", line 94, in __getitem__
    if self.__contains__(nodeid):
  File "C:\Users\Arsalan\Anaconda3\envs\RL_Project_S19\lib\site-packages\pyswmm\nodes.py", line 91, in __contains__
    return self._model.ObjectIDexist(ObjectType.NODE.value, nodeid)
  File "C:\Users\Arsalan\Anaconda3\envs\RL_Project_S19\lib\site-packages\pyswmm\swmm5.py", line 675, in ObjectIDexist
    index = self.SWMMlibobj.project_findObject(objecttype, C_ID)
OSError: exception: access violation reading 0x0000000000002DE8

**Comment by bemcdonnell** [comment]
So no rpt file is created? The issue you’re seeing here depends on the fact that your model isn’t opening. Usually the rpt file says what the error is. The access warning is due to the fact that the error wasn’t caught and thrown. Since it wasn’t caught, the node object tried to access node information that didn’t exist in memory.

**Comment by arashtavakoli** [comment]
Would it be a problem to use this code on 64 bit Python? i have already copied that DLL file but I guess that is the issue and why I am not able to run it

**Comment by bemcdonnell** [comment]
Yes. Pyswmm is currently only compatible with 32bit python.

**Comment by arashtavakoli** [comment]
Cause there is not a tensorflow pip for 32 bit python...or maybe I am horribly confused. Thanks a lot for all the answers

**Comment by sjhabedin** [comment]
its working for me now.

**Comment by bemcdonnell** [comment]
@sjhabedin, glad to hear. There is going to be a big release coming out soon that we hope to rectify all these issues.  Stay tuned :-)
