### ISSUE TITLE
swmm5.so: undefined symbol: __pow_finite

### ISSUE THREAD

**Issue by lrntct** [OpenWaterAnalytics/pyswmm#239]
**Describe the bug**
On 0.6.0 installed from pypi, pyswmm fails with an error from the SWMM binary:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/laurent/software/pyswmm_env/lib/python3.8/site-packages/pyswmm/simulation.py", line 68, in __init__
    self._model = PySWMM(inputfile, reportfile, outputfile, swmm_lib_path)
  File "/home/laurent/software/pyswmm_env/lib/python3.8/site-packages/pyswmm/swmm5.py", line 141, in __init__
    self.SWMMlibobj = ctypes.CDLL(swmm_lib_path)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/laurent/software/pyswmm_env/lib/python3.8/site-packages/pyswmm/lib/linux/swmm5.so: undefined symbol: __pow_finite
```

**To Reproduce**
```
import pyswmm
pyswmm.Simulation('')
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.4
 - Python Version 3.8.2 [GCC 9.3.0]
 - PySWMM Version pyswmm-0.6.0-py2.py3-none-any.whl

**Additional context**
Compiling the swmm binary from source solves the issue.

**Comment by lrntct** [comment]
Possibly related: #186 #216
