### ISSUE TITLE
readthedocs build is broken

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/pyswmm#268]
```
Running Sphinx v1.8.5
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyswmm/envs/v1.0.1/lib/python3.7/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyswmm/envs/v1.0.1/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyswmm/checkouts/v1.0.1/docs/source/conf.py", line 24, in <module>
    import pyswmm
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyswmm/envs/v1.0.1/lib/python3.7/site-packages/pyswmm-1.0.1-py3.7.egg/pyswmm/__init__.py", line 11, in <module>
    from pyswmm.links import Link, Links
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyswmm/envs/v1.0.1/lib/python3.7/site-packages/pyswmm-1.0.1-py3.7.egg/pyswmm/links.py", line 12, in <module>
    from pyswmm.swmm5 import PYSWMMException
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyswmm/envs/v1.0.1/lib/python3.7/site-packages/pyswmm-1.0.1-py3.7.egg/pyswmm/swmm5.py", line 20, in <module>
    from swmm.toolkit import solver
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyswmm/envs/v1.0.1/lib/python3.7/site-packages/swmm/toolkit/solver.py", line 33, in <module>
    _solver = swig_import_helper()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyswmm/envs/v1.0.1/lib/python3.7/site-packages/swmm/toolkit/solver.py", line 29, in swig_import_helper
    _mod = imp.load_module('_solver', fp, pathname, description)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyswmm/envs/v1.0.1/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyswmm/envs/v1.0.1/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libswmm5.so: cannot open shared object file: No such file or directory
```

**Comment by bemcdonnell** [comment]
Closed by #309
