### ISSUE TITLE
Failed installation for the latest version

### ISSUE THREAD

**Issue by jlonghku** [OpenWaterAnalytics/pyswmm#270]
**Describe the bug**
Hi, I tried to install the newest verison 1.0.1 with pip (also tried pip3), but it failed. 
I am working with ubuntu 18.04 and run the command pip install pyswmm as the guide said
Here is the log I got:
```
Building wheel for swmm-toolkit (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmp4_6ebtw9 build_wheel /tmp/tmpw8tgf9ud
       cwd: /tmp/pip-install-3i7d1hqb/swmm-toolkit
  Complete output (82 lines):
  Not searching for unused variables given on the command line.
  -- The C compiler identification is GNU 7.5.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- The CXX compiler identification is GNU 7.5.0
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/pip-install-3i7d1hqb/swmm-toolkit/_cmake_test_compile/build
  -- The C compiler identification is GNU 7.5.0
  -- The CXX compiler identification is GNU 7.5.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found Python: /usr/bin/python3 (found suitable version "3.8.5", minimum required is "3.8.5") found components: Interpreter Development Development.Module Development.Embed
  CMake Error at /tmp/pip-build-env-quswevrh/overlay/lib/python3.8/site-packages/cmake/data/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
    Could NOT find SWIG (missing: SWIG_EXECUTABLE SWIG_DIR)
  Call Stack (most recent call first):
    /tmp/pip-build-env-quswevrh/overlay/lib/python3.8/site-packages/cmake/data/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
    /tmp/pip-build-env-quswevrh/overlay/lib/python3.8/site-packages/cmake/data/share/cmake-3.18/Modules/FindSWIG.cmake:105 (find_package_handle_standard_args)
    CMakeLists.txt:25 (find_package)


  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-install-3i7d1hqb/swmm-toolkit/_skbuild/linux-x86_64-3.8/cmake-build/CMakeFiles/CMakeOutput.log".
  /usr/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'cmake_process_manifest_hook'
    warnings.warn(msg)
    File "/tmp/pip-build-env-quswevrh/overlay/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 582, in setup
      env = cmkr.configure(cmake_args,
    File "/tmp/pip-build-env-quswevrh/overlay/lib/python3.8/site-packages/skbuild/cmaker.py", line 229, in configure
      raise SKBuildError(


  --------------------------------------------------------------------------------
  -- Trying "Unix Makefiles" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "Unix Makefiles" generator - success
  --------------------------------------------------------------------------------

  Configuring Project
    Working directory:
      /tmp/pip-install-3i7d1hqb/swmm-toolkit/_skbuild/linux-x86_64-3.8/cmake-build
    Command:
      cmake /tmp/pip-install-3i7d1hqb/swmm-toolkit -G 'Unix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-3i7d1hqb/swmm-toolkit/_skbuild/linux-x86_64-3.8/cmake-install -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3 -DPYTHON_VERSION_STRING:STRING=3.8.5 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.8 -DPYTHON_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libpython3.8.so -DSKBUILD:BOOL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-quswevrh/overlay/lib/python3.8/site-packages/skbuild/resources/cmake -DCMAKE_BUILD_TYPE:STRING=Release

  Traceback (most recent call last):

  An error occurred while configuring with CMake.
    Command:
      cmake /tmp/pip-install-3i7d1hqb/swmm-toolkit -G 'Unix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-3i7d1hqb/swmm-toolkit/_skbuild/linux-x86_64-3.8/cmake-install -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3 -DPYTHON_VERSION_STRING:STRING=3.8.5 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.8 -DPYTHON_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libpython3.8.so -DSKBUILD:BOOL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-quswevrh/overlay/lib/python3.8/site-packages/skbuild/resources/cmake -DCMAKE_BUILD_TYPE:STRING=Release
    Source directory:
      /tmp/pip-install-3i7d1hqb/swmm-toolkit
    Working directory:
      /tmp/pip-install-3i7d1hqb/swmm-toolkit/_skbuild/linux-x86_64-3.8/cmake-build
  Please see CMake's output for more information.
  ----------------------------------------
  ERROR: Failed building wheel for swmm-toolkit
Failed to build swmm-toolkit
ERROR: Could not build wheels for swmm-toolkit which use PEP 517 and cannot be installed directly
```
Is it a bug or anyone can help fix the problem?

**Comment by jennwuu** [comment]
@jlonghku pyswmm installation for linux is an known issue for swmm-python:
https://github.com/OpenWaterAnalytics/swmm-python/issues/59

I would suggest using v0.6.3 for now. Thanks!

**Comment by michaeltryby** [comment]
@jlonghku from the build log it appears that it is trying to build swmm-toolkit from source but SWIG dependency is missing. Install SWIG "sudo apt install swig" and the build should work for you.

**Comment by jlonghku** [comment]
Thanks so much! I will try it.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
