### ISSUE TITLE
Can't run after pyinstaller

### ISSUE THREAD

**Issue by HorbinXx** [OpenWaterAnalytics/pyswmm#305]
**Describe the bug**
I can't run .exe after pack my code with pyinstaller

**To Reproduce**
I simplely download the code in document named "print_runoff.py".
(https://pyswmm.readthedocs.io/en/stable/examples/examples.html)
And it works well by using "python print_runoff.py".
After "pyinstaller -F print_runoff.py", like:
```
PS E:\calibration> pyinstaller -F .\print_runoff.py
54 INFO: PyInstaller: 4.7
54 INFO: Python: 3.9.9
62 INFO: Platform: Windows-10-10.0.22000-SP0
63 INFO: wrote E:\calibration\print_runoff.spec
65 INFO: UPX is not available.
78 INFO: Extending PYTHONPATH with paths
['E:\\calibration']
236 INFO: checking Analysis
236 INFO: Building Analysis because Analysis-00.toc is non existent
236 INFO: Initializing module dependency graph...
238 INFO: Caching module graph hooks...
248 INFO: Analyzing base_library.zip ...
1634 INFO: Processing pre-find module path hook distutils from 'D:\\Interpreter\\Python39\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
1635 INFO: distutils: retargeting to non-venv dir 'D:\\Interpreter\\Python39\\lib'
3465 INFO: Caching module dependency graph...
3573 INFO: running Analysis Analysis-00.toc
3575 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by D:\Interpreter\Python39\python.exe
3728 INFO: Analyzing E:\calibration\print_runoff.py
3914 INFO: Processing module hooks...
3914 INFO: Loading module hook 'hook-difflib.py' from 'D:\\Interpreter\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
3915 INFO: Loading module hook 'hook-distutils.py' from 'D:\\Interpreter\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
3916 INFO: Loading module hook 'hook-distutils.util.py' from 'D:\\Interpreter\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
3917 INFO: Loading module hook 'hook-encodings.py' from 'D:\\Interpreter\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
3977 INFO: Loading module hook 'hook-heapq.py' from 'D:\\Interpreter\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
3978 INFO: Loading module hook 'hook-lib2to3.py' from 'D:\\Interpreter\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
4076 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'D:\\Interpreter\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
4077 INFO: Loading module hook 'hook-pickle.py' from 'D:\\Interpreter\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
4078 INFO: Loading module hook 'hook-sqlite3.py' from 'D:\\Interpreter\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
4141 INFO: Loading module hook 'hook-sysconfig.py' from 'D:\\Interpreter\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
4142 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'D:\\Interpreter\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
4142 INFO: Loading module hook 'hook-xml.py' from 'D:\\Interpreter\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
4180 INFO: Looking for ctypes DLLs
4190 INFO: Analyzing run-time hooks ...
4192 INFO: Including run-time hook 'D:\\Interpreter\\Python39\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgutil.py'
4195 INFO: Including run-time hook 'D:\\Interpreter\\Python39\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
4196 INFO: Including run-time hook 'D:\\Interpreter\\Python39\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
4200 INFO: Looking for dynamic libraries
4257 WARNING: lib not found: swmm5.dll dependency of D:\Interpreter\Python39\lib\site-packages\swmm\toolkit\_solver.cp39-win_amd64.pyd
4292 INFO: Looking for eggs
4293 INFO: Using Python library D:\Interpreter\Python39\python39.dll
4293 INFO: Found binding redirects:
[]
4298 INFO: Warnings written to E:\calibration\build\print_runoff\warn-print_runoff.txt
4336 INFO: Graph cross-reference written to E:\calibration\build\print_runoff\xref-print_runoff.html
4341 INFO: checking PYZ
4341 INFO: Building PYZ because PYZ-00.toc is non existent
4342 INFO: Building PYZ (ZlibArchive) E:\calibration\build\print_runoff\PYZ-00.pyz
4712 INFO: Building PYZ (ZlibArchive) E:\calibration\build\print_runoff\PYZ-00.pyz completed successfully.
4718 INFO: checking PKG
4718 INFO: Building PKG because PKG-00.toc is non existent
4719 INFO: Building PKG (CArchive) print_runoff.pkg
6134 INFO: Building PKG (CArchive) print_runoff.pkg completed successfully.
6136 INFO: Bootloader D:\Interpreter\Python39\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
6136 INFO: checking EXE
6136 INFO: Building EXE because EXE-00.toc is non existent
6136 INFO: Building EXE from EXE-00.toc
6136 INFO: Copying bootloader EXE to E:\calibration\dist\print_runoff.exe
6144 INFO: Copying icon to EXE
6144 INFO: Copying icons from ['D:\\Interpreter\\Python39\\lib\\site-packages\\PyInstaller\\bootloader\\images\\icon-console.ico']
6145 INFO: Writing RT_GROUP_ICON 0 resource with 104 bytes
6145 INFO: Writing RT_ICON 1 resource with 3752 bytes
6145 INFO: Writing RT_ICON 2 resource with 2216 bytes
6145 INFO: Writing RT_ICON 3 resource with 1384 bytes
6145 INFO: Writing RT_ICON 4 resource with 37019 bytes
6145 INFO: Writing RT_ICON 5 resource with 9640 bytes
6145 INFO: Writing RT_ICON 6 resource with 4264 bytes
6145 INFO: Writing RT_ICON 7 resource with 1128 bytes
6150 INFO: Copying 0 resources to EXE
6150 INFO: Emedding manifest in EXE
6151 INFO: Updating manifest in E:\calibration\dist\print_runoff.exe
6151 INFO: Updating resource type 24 name 1 language 0
6155 INFO: Appending PKG archive to EXE
7067 INFO: Building EXE from EXE-00.toc completed successfully.
```
I can't run the "print_runoff.exe", like:
```
PS E:\calibration\dist> .\print_runoff.exe
Traceback (most recent call last):
  File "print_runoff.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "pyswmm\__init__.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "pyswmm\links.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "swmm\toolkit\__init__.py", line 39, in <module>
  File "os.py", line 1111, in add_dll_directory
FileNotFoundError: [WinError 2] 系统找不到指定的文件。(English: System can't find the file.): 'C:\\Users\\Horbin\\AppData\\Local\\Temp\\_MEI77322\\swmm\\toolkit\\../../swmm_toolkit'
[7700] Failed to execute script 'print_runoff' due to unhandled exception!
```
I think the problem is caused by code in './swmm/toolkit/__init__.py':
```
# Adds directory containing swmm libraries to path
if platform.system() == "Windows":
    libdir = os.path.join(os.path.dirname(__file__), "../../swmm_toolkit")

    if hasattr(os, 'add_dll_directory'):
        os.add_dll_directory(libdir)
    else:
        os.environ["PATH"] = libdir + ";" + os.environ["PATH"]
```
After changing the 'libdir' to direct dir, I fixed the problem temporarily

**Desktop (please complete the following information):**
 - OS: Windows11
 - Python Version [Python 3.9-x64]
 - PySWMM Version [v1.0.1]

**Comment by HorbinXx** [comment]
> @HorbinXx Pyinstaller relocates the libraries. You need to figure out where the required libraries get relocated to by py installer. Modify the _init_.py file to append that location to the path variable and it should work.

Yes, it works well. Thanks for your reply. And I think there may be a better way to avoid change __init__.py, but I can't capture it.

**Comment by michaeltryby** [comment]
It’s ok to change init.py. Path contains multiple places where the system looks for the libraries.

**Comment by michaeltryby** [comment]
So we can close this issue?
