### ISSUE TITLE
Initializing the Model in PySWMM

### ISSUE THREAD

**Issue by Dinho4** [OpenWaterAnalytics/pyswmm#319]
The following is what view whenever I try to Initialize simulation, and don't know how to proceed.

from pyswmm import Simulation, Links, Subcatchments, Nodes, SystemStats

root = 'C:/Users/Malesela/Downloads/'
inpSWMM = 'CIV5000W Simulation Project.inp'

sim = Simulation(root + inpSWMM)

Cannot open input file C:/Users/Malesela/Downloads/CIV5000W Simulation Project.inpTraceback (most recent call last):
File "", line 1, in
File "/root/tutorial_env/lib/python3.9/site-packages/pyswmm/simulation.py", line 69, in init
self._model.swmm_open()
File "/root/tutorial_env/lib/python3.9/site-packages/pyswmm/swmm5.py", line 217, in swmm_open
solver.swmm_open(inpfile, rptfile, binfile)
File "/root/tutorial_env/lib/python3.9/site-packages/swmm/toolkit/solver.py", line 509, in swmm_open
return _solver.swmm_open(f1, f2, f3)
Exception:
ERROR 303: cannot open input file.

**Comment by jennwuu** [comment]
You are seeing this error because pyswmm cannot find the inp file that you provided in the path. 

Can you confirm if path (root + inpSWMM) is correct or if pyswmm installation has access to it?
