### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by lmontest** [OpenWaterAnalytics/pyswmm#79]
```python
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyswmm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyswmm\__init__.py", line 11, in <module>
    from pyswmm.links import Link, Links
  File "pyswmm\pyswmm.py", line 11, in <module>
    from pyswmm.swmm5 import PySWMM
ImportError: No module named swmm5
```

**Comment by goanpeca** [comment]
Hi @lmontest will look into it

**Comment by bemcdonnell** [comment]
He is using py2.7.13(win32) on windows 10
